### PR TITLE
upgarde Hibernate version from 4.1.7.Final to 4.3.10.Final

### PR DESCRIPTION
**Pull request by froque**
EJB3Configuration was removed in Hibernate 4.3, in favor of javax.persistence API

Current way to generate SQL schema is to use JPA 2.1 api:
http://java.dzone.com/articles/generating-database-schemas

But, this doesn't seem to support/use Hibernate Configuration.generateSchemaUpdateScriptList to make only updates. 

So, this pull request copies some code from HibernatePersistenceProvider to use that method.

### CODE REVIEW

**Comment by ajcamilo** [comment]
Can you create some sort of unit test just for future bump versions?

**Comment by froque** [comment]
unit tests done. HibernateEnversDDL requires filename for all commands

**Comment by ajcamilo** [comment]
@froque can you see what happened?

**Comment by froque** [comment]
done

**Pull request merged**
